services:
  - type: web
    name: client
    env: node
    buildCommand: |
      cd client && npm install && npm run build
    startCommand: |
      cd client && npm run start
    port: 3000

  - type: web
    name: server
    env: node
    buildCommand: |
      cd server && npm install
    startCommand: |
      cd server && npm run start
    port: 8080